name: Build on Ubuntu
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Install elm
        run: |
          curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
          gunzip elm.gz
          chmod +x elm
          sudo mv elm /usr/local/bin/
          elm --help
      - name: Install elm-format and elm-test
        run: |
          npm install -g elm-test elm-format
      - name: Simple test
        run: |
          elm-test
